### PR TITLE
HW2_1 branch was created. Files from HW1 were deleted.

### PR DESCRIPTION
**Pull request by RatkevichIlya**
Pull request for HW 2_1.

### CODE REVIEW

**Comment by RatkevichIlya** [comment]
@rinnifox

**Comment by rinnifox** [comment]
Hi Ilya!

Comments regarding your regular expressions:

1. ENSEMBL. Your expression `r'ENS+[A-Z0-9]{11}'` allows to insert `EN` then `S` 1 or more times and then any 11 symbols (letters or numbers), which is incorrect. This does match the given examples because you are not linking your expression to the end of the string with the `$` character. So in fact, for this example `ENSMUSG00000012048` the `ENSMUSG0000001` part is a true match but all the other part remains uncovered (meaning that there can be anything). You can check this [page](https://www.ensembl.org/info/genome/stable_ids/prefixes.html) to get the idea of how ENSEMBL IDs should be constructed, which characters and how many should be there.
2. Uniprot. In yor expression `r'\w{6}` you simply denote any 6 symbols. Are you sure it is a proper way to check for the match with the real database id? Moreover, in the lecture materials I provided a link for Uniprot accession ID construction rules as the actual expression for this database is rather complex, and it is explicitly indicated in the home task file that you should use this materials to complete a correct expression for Uniprot.

Fix this please before the next lecture, ok?

**Comment by RatkevichIlya** [comment]
Hello, @rinnifox! Ok! Done!

**Comment by rinnifox** [comment]
Hi Ilya!

Ok for Uniprot.
For ENSEMBL, now it seems too complex. Can you explain the appearance of symbols FB or Y in your alternative expressions for this database?

**Comment by RatkevichIlya** [comment]
Hi, @rinnifox ! FB is for FlyBase IDs (example: FBgn0000032) and Y is for mRNA splice variants IDs (example: YBR289W)

**Comment by rinnifox** [comment]
Ok. Even though FlyBase is a separate DB, let it be there since these IDs can be also found via ENSEMBL. 

However, I still don't see a match to the main ENSEMBL stable IDs. `(ENS[FPTG]\\d{11}(\\.\\d+)?) `- is it this part? If so, after `ENS` you're indicating `FPTG` symbols, but there are also other letters possible for feature prefixes (they are indicated on the page I've shared in the comment above). Moreover, the amount of these symbols has to be restricted. Then, I don't see a part denoting the species. Finally, I don't get a reason for presence of `\` symbol in between [FPTG] and \d{11}.

**Comment by RatkevichIlya** [comment]
@rinnifox
Ok, done

**Comment by rinnifox** [comment]
`ENS[a-zA-Z\_]*\d{11}` allows you to insert unlimited number of letters (and even 0 is accepted), while in ENSEMBL documentation I've shared above, it is clearly indicated, how many letters is possible to have for feature prefixes and for species as well. I think you have just one more attempt to fix and then I will close this task.

**Comment by RatkevichIlya** [comment]
Done. I hope I've taken everything into account this time.

**Comment by rinnifox** [comment]
Now seems to be correct! You can merge this PR by yourself :)

**Pull request merged**
